rancher/image-build-flannel

- Dockerfile
Signed-off-by: Chris Kim <oats87g@gmail.com>
> Add which for the iptables-detect script

- Dockerfile
- Makefile
The aim is to have dualstack support
Linked issue: https://github.com/rancher/rke2/issues/1883
Signed-off-by: Manuel Buil <mbuil@suse.com>
> Move to a dualStack supported flannel tag

- .drone.yml
Signed-off-by: Manuel Buil <mbuil@suse.com>
> Update version of base image in .drone

- Dockerfile
- Makefile
- README.md
Also update the base image
Issue: https://github.com/rancher/rke2/issues/2599
Signed-off-by: Manuel Buil <mbuil@suse.com>
> Update flannel to 0.17.0

- Dockerfile
- Makefile
- README.md
> Updated flannel to v0.19.1

- Dockerfile
- Makefile
- README.md
Update Flannel version to v0.20.2
> Update flannel to v0.20.2

- .drone.yml
- Dockerfile
- Makefile
- README.md
and update hardened-build-base to v1.19.5b1
> update to flannel v0.21.1

- Dockerfile
- Makefile
- README.md
Update Flannel version to v0.21.3
> Update Flannel to v0.21.3

- Dockerfile
- Makefile
- README.md
> Update flannel to v0.22.1

- .drone.yml
- manifest.tmpl
> Remove s390 build on drone

- .github/workflows/updateversion.yml
The added github action will check each day the latest version on flannel github and in case a new version is released it'll update the build tag on the repo and create a PR.
> Added github action to automate version updates

- .github/workflows/updatek3srootversion.yml
This image consumes k3s-root. We should be aware of when there is a new k3s-root release and create the update. A script can do this
> Add script to update when there is a new k3s-root

- updatecli/updatecli.d/updateflannel.yaml
- updatecli/updatecli.d/updatek3sroot.yaml
Follow along what we are using in other repos
> Get token, user and username from values in updatecli

- updatecli/updatecli.d/updatebuildbase.yaml
This PR also searches for the go version of the upstream project
Works: https://github.com/rancher/image-build-flannel/pull/71
> Use updatecli to update the base image in drone

- Dockerfile
Following on from what was done upstream: https://github.com/flannel-io/flannel/pull/1882
> Remove net-tools from the image

- updatecli/updatecli.d/updatebuildbase.yaml
Updatecli is complaining because it can't find the drone file anymore
> Remove drone from updatecli as well

- Dockerfile
- Makefile
> Update to v0.25.1

- Dockerfile
Update Dockerfile for ARM64 build https://github.com/rancher/rke2/issues/5808
> Updated Dockerfile for arm64 build

- Dockerfile
- Makefile
https://github.com/rancher/rke2/issues/6171
> Move to v0.25.4

- Dockerfile
> Update go version base image

- Dockerfile
Manual bump since updatecli currently has some issues
> Bump hardened-build-base to v1.23.12b1
